### ISSUE TITLE
createTaskPaperOutline('') has different behavior than reloadSerialization('')

### ISSUE THREAD

**Issue by Leftium** [jessegrosjean/birch-outline#5]
`createTaskPaperOutline('')` results in an outline with 0 items, while `reloadSerialization('')` results in an outline with 1 item.
 - I'm not sure what the proper behavior is
 - I think it's a regression from previous versions.
<pre>
> (outline = new birch.Outline.createTaskPaperOutline('')).items.length;
0
> outline.reloadSerialization(''); outline.items.length
1
> outline.items[0].bodyString
''
</pre>

**Compare to:**
<pre>
> (outline = new birch.Outline.createTaskPaperOutline('\n')).items.length;
2
> outline.reloadSerialization('\n'); outline.items.length
2
> (outline = new birch.Outline.createTaskPaperOutline()).items.length;
0
> outline.reloadSerialization(); outline.items.length
0
> (outline = new birch.Outline.createTaskPaperOutline(' ')).items.length;
1
> outline.reloadSerialization(' '); outline.items.length
1
</pre>

**Comment by jessegrosjean** [comment]
I've just fixed this internally, though will be sometime before I publish fix. The issue was changing Outline constructor code:

```
if serialization
  @reloadSerialization(serialization)
```

To:

```
if serialization?
  @reloadSerialization(serialization)
```

The end result is a new outline with content should always have at least 1 nodes.
