### ISSUE TITLE
Inconsistent (mis)spelling in API

### ISSUE THREAD

**Issue by Leftium** [jessegrosjean/birch-outline#6]
Some (undocumented) API's have unfortunate naming errors. "flattended" should be "flattened"

Because both variations of the (mis)spelling are used, it is very confusing!

1. "flattened"
    - flattenedRemovedItems
2. "Flattended"
    - flattendedAddedItems
    - getFlattendedAddedItems
    - getFlattendedAddedItemIDs
    - getFlattendedRemovedItems
    - getFlattendedRemovedItemIDs

**Comment by jessegrosjean** [comment]
Thanks, spelling and I have a long history :) I've fixed this internally. I'll eventually publish the fix, but will take a while (I'm in the middle of big hackings at the moment)
