### ISSUE TITLE
getting started page

### ISSUE THREAD

**Issue by derickfay** [jessegrosjean/birch-outline#7]
I was starting to play with this and found a few broken links

[birch-outline/getting-started.md](https://github.com/jessegrosjean/birch-outline/blob/master/doc/getting-started.md)
links to
[documented API](https://github.com/jessegrosjean/birch-outline/blob/master/doc/api.md) which gives a 404 

and the web page sample refers to a file `birch-outline/min/birchoutline.js` which doesn't exist, unless I'm missing something.

**Comment by jessegrosjean** [comment]
Thanks, I've fixed the 404 link. For `birch-outline/min/birchoutline.js` you need to do `npm install` (from the "getting started page docs") first. Then it should show up.
